application: overnumerousness-site
version: overnumerousness-joomla-site-1
runtime: php
api_version: 1
threadsafe: true

#handlers:
# Regular expression of uri to match for this script
#- url: .*
# Path to script to execute for this uri
#  script: gae/main.php
# Use HTTPS: never, always, or optional
#  secure: never
# Google App Logon config: optional, required, admin [required and must be app admin]
#  login: optional

# For maintenability, handlers are kept in seperate files and included here.  All handlers should be placed in the gae/app.yaml.d subdirectory and then included here

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: /favicon\.ico

includes:
# Media file paths have to be placed first
- gae/app.yaml.d/joomla-media.yaml

# phpinfo page
- gae/app.yaml.d/info.yaml
# various function, class, header dumpage page
- gae/app.yaml.d/dump.yaml
# APC cache info
- gae/app.yaml.d/apc.yaml
# phpinfo page
- gae/app.yaml.d/test.yaml
# joomla install
- gae/app.yaml.d/joomla-install.yaml
# joomla admin
- gae/app.yaml.d/joomla-admin.yaml
# joomla site
- gae/app.yaml.d/joomla-site.yaml

