application: overnumerousness-site

# arbitrary string used to identify version
version: overnumerousness-site

# always php for php apps
runtime: php

# always version 1
api_version: 1

# Enables an instance to handle requests at the same time
threadsafe: true

#handlers:
# Regular expression of uri to match for this script
#- url: .*
# Path to script to execute for this uri
#  script: gae/main.php
# Use HTTPS: never, always, or optional
#  secure: never
# Google App Logon config: optional, required, admin [required and must be app admin]
#  login: optional

# For maintenability, handlers are kept in seperate files and included here.  All handlers should be placed in the gae/app.yaml.d subdirectory and then included here

includes:
# Media file paths have to be placed first
- gae/app.yaml.d/joomla-media.yaml

##Non-joomla debugging information pages
# phpinfo page
- gae/app.yaml.d/info.yaml
# various function, class, header dumpage page
- gae/app.yaml.d/dump.yaml
# APC cache info
- gae/app.yaml.d/apc.yaml
# phpinfo page
- gae/app.yaml.d/test.yaml


##Joomla pages
# joomla install
- gae/app.yaml.d/joomla-install.yaml
# joomla admin
- gae/app.yaml.d/joomla-admin.yaml
# joomla site
- gae/app.yaml.d/joomla-site.yaml

## Additional services
# Pagespeed has to be IN app.yaml, so it is copied from this file
#- gae/app.yaml.d/pagespeed.yaml
#pagespeed:
